version: '3.7'
services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INIT_DATABASE: rest
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8000:8000
    volumes:
      - .:/app
    links:
      - mongo